

datasets:
	cd Groceries; R --vanilla < Groceries.R; mv Groceries.rda ../../data/; 
	cd Income; R --vanilla < Income.R; mv Income.rda ../../data/; mv IncomeESL.rda ../../data/
	cd Adult; R --vanilla < Adult.R; mv Adult.rda ../../data/; mv AdultUCI.rda ../../data/
	cd epub; R --vanilla < epub.R; mv Epub.rda ../../data/
	cd SunBai; R --vanilla < SunBai.R; mv SunBai.rda ../../data/
	cd Mushroom; R --vanilla < Mushroom.R; mv Mushroom.rda ../../data/
